version: "3"

services:

  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: exec_module # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: exec_module1010# # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: exec_module # The PostgreSQL default database (automatically created at first launch)
    
